#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	sudo="sudo -E"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	hi="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	P="sudo pacman -S" \
	q="exit" \
	snh="sudo nvim /etc/hosts" \
	his="nvim /home/$USER/.cache/zsh/history.sh" \
	skkshu="ranger $HOME/Github/skkshu.github.io/" \
	hosts="sudo wget https://raw.githubusercontent.com/racaljk/hosts/master/hosts -O /etc/hosts" \
	s="neofetch" \
	cs="clear && neofetch" \
	ra="ranger" \
	n="nvim" \
	lg="lazygit" \
	smci="sudo make clean install" \
	c="clear" \
	sr="sudo -E ranger" \
	jks="cd $HOME/skkshu.github.io && jekyll serve" \
	t="tldr" \
	x="startx" \
	swap="ranger $XDG_CONFIG_HOME/nvim/tmp/backup" \
	gc="git clone" \
	gC="git config credential.helper store"
	#ssn="sudo shutdown -h now"

alias \
	coz="nvim $XDG_CONFIG_HOME/zsh/.zshrc" \
	coza="nvim $XDG_CONFIG_HOME/zsh/aliasrc" \
	con="nvim $XDG_CONFIG_HOME/nvim/init.vim" \
	cor="nvim $XDG_CONFIG_HOME/ranger/rc.conf" \
	cdz="cd $XDG_CONFIG_HOME/zsh"

#cd
alias \
	cdn="cd $XDG_CONFIG_HOME/nvim" \
	cdc="cd $XDG_CONFIG_HOME" \
	iu="chromium --proxy-server="http://127.0.0.1:2000" &"

#coa="nvim $XDG_CONFIG_HOME/alacritty/alacritty.yml" \
#cor="nvim $XDG_CONFIG_HOME/ranger/rc.conf" \
#coi="nvim $XDG_CONFIG_HOME/i3/config" \
#s="neofetch --ascii_distro arch" \
# his="nvim $XDG_CONFIG_HOME/zsh/.zsh_history" \
